[package]
name = "server"
version = "0.1.0"
authors = ["Igor Anic <ianic@inet.hr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.8.2"
hex-literal = "0.2.1"
base64 = "0.12.0"